import pytest
from unittest.mock import patch, MagicMock
from db.models import Lead
from ai_agent.backend.service import AiAgentService

@pytest.fixture
def mock_db():
    return MagicMock()

@pytest.mark.asyncio
async def test_lead_create_auto_open(mock_db):
    mock_lead = Lead(id="L1", last_name="Hong", status="New")
    
    with patch("ai_agent.backend.service.IntentPreClassifier.detect", return_value=None):
        with patch("ai_agent.backend.service.AiAgentService._call_multi_llm_ensemble", return_value={"intent": "CREATE", "object_type": "lead", "data": {"last_name": "Hong"}}):
            with patch("web.backend.app.services.lead_service.LeadService.create_lead", return_value=mock_lead):
                response = await AiAgentService.process_query(
                    db=mock_db,
                    user_query="create lead Hong",
                    conversation_id="conv-1"
                )
                
                assert response["intent"] == "CREATE"
                assert response.get("auto_open") is True
                assert response.get("record_id") == "L1"

@pytest.mark.asyncio
async def test_lead_update_auto_open(mock_db):
    mock_lead = Lead(id="L1", last_name="Hong", status="Qualified")
    
    with patch("ai_agent.backend.service.IntentPreClassifier.detect", return_value=None):
        with patch("ai_agent.backend.service.AiAgentService._call_multi_llm_ensemble", return_value={"intent": "UPDATE", "object_type": "lead", "record_id": "L1", "data": {"status": "Qualified"}}):
            with patch("web.backend.app.services.lead_service.LeadService.update_lead", return_value=True):
                with patch("web.backend.app.services.lead_service.LeadService.get_lead", return_value=mock_lead):
                    response = await AiAgentService.process_query(
                        db=mock_db,
                        user_query="update lead L1 to Qualified",
                        conversation_id="conv-1"
                    )
                    
                    assert response["intent"] == "UPDATE"
                    assert response.get("auto_open") is True
                    assert response.get("record_id") == "L1"

@pytest.mark.asyncio
async def test_global_search_intent(mock_db):
    # Testing how the backend handles the query generated by handleAgentGlobalSearch
    with patch("ai_agent.backend.service.IntentPreClassifier.detect", return_value={"intent": "QUERY", "object_type": "lead"}):
        with patch("ai_agent.backend.service.AiAgentService._execute_paginated_query", return_value={"results": [], "sql": "SELECT...", "pagination": {}}):
            response = await AiAgentService.process_query(
                db=mock_db,
                user_query='search lead for "test"',
                conversation_id="conv-1"
            )
            assert response["intent"] == "QUERY"
            assert response["object_type"] == "lead"

@pytest.mark.asyncio
async def test_object_type_normalization(mock_db):
    # Testing that 'leads' is normalized to 'lead' in the response
    with patch("ai_agent.backend.service.IntentPreClassifier.detect", return_value={"intent": "QUERY", "object_type": "leads"}):
        with patch("ai_agent.backend.service.AiAgentService._execute_paginated_query", return_value={"results": [], "sql": "SELECT...", "pagination": {}}):
            response = await AiAgentService.process_query(
                db=mock_db,
                user_query="all leads",
                conversation_id="conv-1"
            )
            # The singularization logic in _execute_intent should have turned 'leads' into 'lead'
            assert response["object_type"] == "lead"
